name: mode_theme
description: Flutter Package to handle light/dark themes
version: 0.2.0+3
author: Steven Smith
homepage: https://www.icodeforyou.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
